#!/bin/bash

#$1 is the name of the file

# check that the number of arguments is 1 (Step 1)
if (($# != 1)) || test ! -f $1; then 
# check that the file exists (Step 1)
  echo $1 'does not exist or cannot be opened'
  exit -1
fi
# extract all of the Reader Messages (R) (Step 1)
echo "Extrating Reader Messages"
grep '^.\[[01];[0-9][0-9]mR' $1 > $1.Reader
# add time range to end of file. (Step 3)
startTime=`head -n 1 $1.Reader | grep -Eo '[0-9]+\.[0-9]+' | sed 's/\.//'`
endTime=`tail -n 1 $1.Reader | grep -Eo '[0-9]+\.[0-9]+' | sed 's/\.//'`
printf "Time span: %.2f\n" "$(($endTime-$startTime))e-6" >> $1.Reader

# extract all of the Printer Messages (P)  (Step 1)
echo "Extrating Summary Printer Messages"
grep '^.\[[01];[0-9][0-9]mP' $1 > $1.Printer
# add time range to end of file. (Step 3)
startTime=`head -n 1 $1.Printer | grep -Eo '[0-9]+\.[0-9]+' | sed 's/\.//'`
endTime=`tail -n 1 $1.Printer | grep -Eo '[0-9]+\.[0-9]+' | sed 's/\.//'`
printf "Time span: %.2f\n" "$(($endTime-$startTime))e-6" >> $1.Printer

#find the number of machines (Step 2)
monlist=`grep '^.\[[01];[0-9][0-9]m[0-5]' $1 | cut -b 8 | sort -u`
# extract each machine messages (Step 2)
for i in $monlist ; do
  echo "Extracting Machine "$i"'s Messages"
  grep '^.\[[01];[0-9][0-9]m'$i $1 > $1.thread$i
done

